<Project Sdk="Microsoft.NET.Sdk.Web">

<PropertyGroup>
  <TargetFramework>net8.0</TargetFramework>
  <RuntimeIdentifiers>win-x86</RuntimeIdentifiers>
  <Nullable>enable</Nullable>
  <ImplicitUsings>enable</ImplicitUsings>
</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire" Version="1.8.22" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.22" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.15" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Filters\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartTaskOptimizer.Application\SmartTaskOptimizer.Application.csproj" />
    <ProjectReference Include="..\SmartTaskOptimizer.Infrastructure\SmartTaskOptimizer.Infrastructure.csproj" />
    <ProjectReference Include="..\SmartTaskOptimizer.Shared\SmartTaskOptimizer.Shared.csproj" />
  </ItemGroup>

</Project>
